apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-backup-s3
spec:
  {{- if .Values.timeZone }}
  timeZone: {{ .Values.timeZone }}
  {{- end }}
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  startingDeadlineSeconds: 90
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: argocd-backup-s3
          containers:
            - name: argocd-backup-s3
              image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext: {{ toYaml .Values.securityContext | nindent 16 }}
              {{- if .Values.secretEnvVars }}
              envFrom:
              - secretRef:
                  name: argocd-backup-s3-secret-env-vars
              {{- end }}
              {{- if .Values.envVarSecretReferences }}
              env:
                {{- toYaml .Values.envVarSecretReferences | nindent 14 }}
              {{- end }}
              {{- if .Values.custom_command }}
              command: 
                {{- toYaml .Values.custom_command | nindent 14 }}
              {{- end }}
              {{- if .Values.resources }}
              resources: {{- toYaml .Values.resources | nindent 16 }}
              {{- end }}
          restartPolicy: OnFailure

