{{- if (.Values.secretEnvVars) -}}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-backup-s3-secret-env-vars
type: Opaque
stringData: {{ toYaml .Values.secretEnvVars | nindent 2}}
{{- end }} {{/* end of if secretEnvVars */}}