apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argocd-backup-s3
  annotations:
    {{- if .Values.serviceAccount.irsaEnabled }}
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.irsaRoleArn }}"
    {{- end }}