apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argocd-backup-s3
  {{- if .Values.serviceAccount.irsaEnabled }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.irsaRoleArn }}"
  {{- end }}